### ISSUE TITLE
Generating piece metadata in pyspool and spoolio may be inconsistent

### ISSUE THREAD

**Issue by TimDaub** [ascribe/pyspool#51]
Here: https://github.com/ascribe/pyspool/blob/f8b10df1e7d2ea7950dde433c1cb6d5225112f4f/spool/file.py#L91 to generate the piece's metadata, all keys given as kwargs are sorted, whereas it seems this implementation was never directly used in spoolio. There, the keys used to generate metadata are in the following order: https://github.com/ascribe/spoolio-copy/blob/05d9559503e26ca03a436acfdedb30f0a9f3ca75/piece/models.py#L96

Note that e.g. "title" is put before "artist_name". So I think the implementations diverge.

@sbellem and @r-marques can you maybe comment which implementation ended up getting used in practice? I'd guess that it was the one in spoolio, right?

**Comment by TimDaub** [comment]
My goal is to recreate the BTC addresses used to register a piece. Through a lucky incident, I ended up downloading my metadata for that piece. The metadata is:

```js
{"piece":{"id":17089,"title":"Copying the Scream","artist_name":"Tim Daubenschütz","thumbnail":{"id":8393,"url":"https:
//d1qjsxua1o9x03.cloudfront.net/media/thumbnails/ascribe_spiral.png","url_safe":"https://d1qjsxua1o9x03.cloudfront.net/me
dia%2Fthumbnails%2Fascribe_spiral.png","mime":"image","thumbnail_sizes":{"100x100":"https://d1qjsxua1o9x03.cloudfront.net
/live/42a0e188f5033bc65bf8d78622277c4e/7eab923d-e9cf-43a1-9650-0b6e416fbea3/digitalwork/7eab923d-e9cf-43a1-9650-0b6e416fb
ea3-b4568e5b-bac8-4cec-94f0-c75115893980.gif","300x300":"https://d1qjsxua1o9x03.cloudfront.net/live/42a0e188f5033bc65bf8d
78622277c4e/7eab923d-e9cf-43a1-9650-0b6e416fbea3/digitalwork/7eab923d-e9cf-43a1-9650-0b6e416fbea3-b4568e5b-bac8-4cec-94f0
-c75115893980.gif","600x600":"https://d1qjsxua1o9x03.cloudfront.net/live/42a0e188f5033bc65bf8d78622277c4e/7eab923d-e9cf-4
3a1-9650-0b6e416fbea3/digitalwork/7eab923d-e9cf-43a1-9650-0b6e416fbea3-b4568e5b-bac8-4cec-94f0-c75115893980.gif"}},"bitco
in_id":"17xPxYhKcFPu84CcXVSHgRyTQ654QrqAPB","num_editions":10,"user_registered":"Tim Daubenschütz","datetime_registered":
"2016-01-31T18:50:31.025482Z","date_created":"2016-01-01","license_type":{"name":"All rights reserved","code":"default","
organization":"ascribe","url":"https://www.ascribe.io/faq/#legals"},"acl":{"acl_view_editions":true},"extra_data":{},"dig
ital_work":{"id":9625,"url":"https://d1qjsxua1o9x03.cloudfront.net/live/42a0e188f5033bc65bf8d78622277c4e/7eab923d-e9cf-43
a1-9650-0b6e416fbea3/digitalwork/7eab923d-e9cf-43a1-9650-0b6e416fbea3-b4568e5b-bac8-4cec-94f0-c75115893980.gif","url_safe
":"https://d1qjsxua1o9x03.cloudfront.net/live%2F42a0e188f5033bc65bf8d78622277c4e%2F7eab923d-e9cf-43a1-9650-0b6e416fbea3%2
Fdigitalwork%2F7eab923d-e9cf-43a1-9650-0b6e416fbea3-b4568e5b-bac8-4cec-94f0-c75115893980.gif","mime":"image","hash":"efec
f9b7933f0b4727376b86e5a14c65","encoding_urls":null,"isEncoding":0},"other_data":[],"loan_history":[],"private_note":null,
"public_note":null,"notifications":[]},"success":true}
```

File: https://drive.google.com/file/d/1s-hz0GpMOGuzKvj-bL2YX8Mp4MW5zWoQ/view?usp=sharing though I'm not sure if Google Drive does processing on the image. If you want it, feel free to email me.

I also have the file still, its hash is "e9dd999e8ed1ef7975811e838458cf03" and the resulting BTC address is "1FoESEauTSR6sJauxvknuYoNdvSmp1FUtB", which checks out on BTC: https://www.blockchain.com/btc/address/1FoESEauTSR6sJauxvknuYoNdvSmp1FUtB

But I'm failing to canonicalize the meta data hashing and the resulting BTC metadata address. Also: How did the `bitcoin_path` https://github.com/ascribe/spoolio-copy/blob/05d9559503e26ca03a436acfdedb30f0a9f3ca75/piece/models.py#L101 here generated? It seems it was split up with ":" and the first item was the `bitcoin_id` https://github.com/ascribe/spoolio-copy/blob/05d9559503e26ca03a436acfdedb30f0a9f3ca75/piece/models.py#L67 but what was at `bitcoin_path.split(':')[0]`

Edit: Could be that `bitcoin_path` was a HD derivation path as e.g. shown here: https://learnmeabitcoin.com/technical/derivation-paths

Edit2: Looks like the `bitcoin_path` was derived from a time stamp: https://github.com/ascribe/pyspool/blob/f8b10df1e7d2ea7950dde433c1cb6d5225112f4f/spool/wallet.py#L55

**Comment by r-marques** [comment]
That's all correct. We should have documented on the spec how things where hashed.

The bitcoin_path was stored on the database so there is really no way to recreate it.

If you want only the addresses I would check the op_returns of transactions coming from the ascribe wallet an then search for the `ASCRIBESPOOL01PIECE` verbs. If I'm not mistaken the piece is sent from the ascribe wallet to the new address from the hd wallet

**Comment by TimDaub** [comment]
But do you agree that the bitcoin path was derived from a datatime + the public bitcoin address (called `bitcoin_id` in my metadata)? Because if so e.g. for my piece that was created on 2016-01-01, it'd be fairly trivial to bruce force the hours, minutes, seconds and milliseconds as is shown here: https://github.com/ascribe/pyspool/blob/f8b10df1e7d2ea7950dde433c1cb6d5225112f4f/spool/wallet.py#L55

and given that we can find the tx with the piece registration spool verb where the second output is the metadata address.

**Comment by r-marques** [comment]
That's a good idea
I don't remember exactly how the path was generated but that seems correct. By using a timestamp we didn't have to worry about duplicate paths

**Comment by TimDaub** [comment]
awesome, thanks for helping. I'll try to find some time to brute force the path and I'll update with a script here potentially

**Comment by TimDaub** [comment]
So I looked into brute-forcing and created a little script over on my fork: https://github.com/TimDaub/pyspool/
You can see that this tx is ASCRIBESPOOL01PIECE the https://opreturn.net/e8dd2f5a7fa21a52bf9b6fec1a2ee6bcceda885adfa32f63b99aa37fde36a424 where the second output is the value we're looking for according to [`register_piece`](https://github.com/ascribe/pyspool/blob/f8b10df1e7d2ea7950dde433c1cb6d5225112f4f/spool/spool.py#L99).

It's a naive approach that doesn't use multiple cores but on my old MacBook pro, I was able to generate roughly 12k hashes/s. I ended up saving lots of cycles by not hashing the file each time but just by providing the file hash directly. Maybe this link works for comparing: https://github.com/ascribe/pyspool/compare/master...TimDaub:master

But on my old MacBook Pro, this means that the script would take worst case 80 days to find the solution. I'm sure on a more powerful machine and by utilizing all cores, this could be done much faster. Also, I'm pretty sure, I registered the piece while I was awake so between 8am and 1am during the day of 2016-01-01.

**Comment by TimDaub** [comment]
continuing here: https://github.com/ascribe-archeologists/reverse
